---
apiVersion: v1
kind: Service
metadata:
  name: translator-anki
spec:
  type: LoadBalancer
  selector:
    app: translator-anki
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator-anki
  labels:
    app: translator-anki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translator-anki
  template:
    metadata:
      labels:
        app: translator-anki
    spec:
      containers:
        - name: translator
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/translator/anki:latest