server:
  port: ${PORT:8080}

logging:
  level:
    org.atmosphere: warn
    root: INFO

spring:
  mustache:
    check-template-location: false
  datasource:
    url: ${SPRING_DATASOURCE_JDBC_URL}
    username: postgres
    password: postgres
#  jpa:
#    defer-datasource-initialization: true
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.yml

vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
  productionMode: true
