server:
  port: ${PORT:8082}

logging:
  level:
    org.atmosphere: warn
    root: INFO

spring:
  mustache:
    check-template-location: false
  datasource:
    url: DICTIONARY_URL
    username: DB_USER
    password: PASS
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.yml
    enabled: false
  kafka:
    bootstrap-servers: KAFKA_SERVER
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false

topic:
  send-analytics: topic-statistics

vaadin:
  launch-browser: false
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
  productionMode: true
