server:
  port: 8081

logging:
  level:
    org.atmosphere: warn
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5431/anki?currentSchema=DICTIONARY
    username: postgres
    password: postgres