name: "Build and Deploy translator application"
run-name: ${{ github.actor }} is learning github actions

on:
  push:
    branches: [ dev, prod ]
#  pull_request:
#    branches: [ prod ]



jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout before deploy
        uses: actions/checkout@v3
      - name: install gcloud cli
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
#          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#          export_default_credentials: "true"

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/prod-393309/translator/translator:latest .
          docker push us-central1-docker.pkg.dev/prod-393309/translator/translator:latest

#          docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/prod-393309/translator:latest .
#          docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/prod-393309/translator:latest