name: "Build and Push to Google Artifact Registry"
run-name: ${{ github.actor }} is learning github actions

on:
  push:
    branches: [ dev, prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout before deploy
        uses: actions/checkout@v3

      - name: test setup secrets
        env:
          DICTIONARY_URL: ${{ secrets.DICTIONARY_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          PASS: ${{ secrets.DB_USER_PASS }}
          KAFKA_SERVER: ${{ secrets.KAFKA_SERVER }}
        working-directory: ./src/main/resources
        run: |
          sed -i "s|DICTIONARY_URL|$DICTIONARY_URL|g" application.yml
          sed -i "s|DB_USER|$DB_USER|g" application.yml
          sed -i "s|PASS|$PASS|g" application.yml
          sed -i "s|KAFKA_SERVER|$KAFKA_SERVER|g" application.yml

      - name: install gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/prod-393309/translator/anki:version1 .
          docker push us-central1-docker.pkg.dev/prod-393309/translator/anki:version1