name: Manual workflow
run-name: ${{ github.actor }} is try to set secrets

on:
  push:
    branches: [ dev, prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout before deploy
        uses: actions/checkout@v3

      - name: test setup secrets
        env:
          DICTIONARY_URL: ${{ secrets.DICTIONARY_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_USER_PASS: ${{ secrets.DB_USER_PASS }}
          KAFKA_SERVER: ${{ secrets.KAFKA_SERVER }}
        working-directory: ./src/main/resources
        run: |
          sed -i "s|DICTIONARY_URL|$DICTIONARY_URL|g" application.yml
          sed -i "s|DB_USER|huyzer|g" application.yml
          sed -i "s|PASS|huepass|g" application.yml
          sed -i "s|KAFKA_SERVER|$KAFKA_SERVER|g" application.yml
          grep "username" application.yml
          grep "password" application.yml
